# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.com.cbim.gateway.admin.domain

# 分页配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.81.3.49:3306/cbim_gateway_admin?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: cbim_gateway_admin
    password: cbim_gateway_admin
    hikari:
      # 最小空闲连接
      minimum-idle: 10
      # 最大连接数
      maximum-pool-size: 20
      # 空闲连接超时时间
      idle-timeout: 500000
      # 连接最大存活时间
      max-lifetime: 500000
      # 连接超时时间
      connection-timeout: 60000
      connection-test-query: SELECT 1
      # 自动提交
      auto-commit: false
  rabbitmq:
    host: 10.81.3.50
    port: 5672
    username: admin
    password: Cbim@2021

management:
  metrics:
    export:
      elastic:
        enabled: false
        host: http://10.81.3.19:9200
        user-name: elastic
        password: elastic